apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: example-sc
provisioner: example.csi.example.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: provisioner-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/controller-publish-secret-name: controller-publish-secret
  csi.storage.k8s.io/controller-publish-secret-namespace:  default
  csi.storage.k8s.io/node-stage-secret-name: node-stage-secret
  csi.storage.k8s.io/node-stage-secret-namespace:  default
  csi.storage.k8s.io/node-publish-secret-name: node-publish-secret-${pv.name}-${pvc.namespace}-${pvc.name}
  csi.storage.k8s.io/node-publish-secret-namespace: default
  csi.storage.k8s.io/fstype: ext4
  parameter1: "p1"
  parameter2: "p2"
volumeBindingMode: WaitForFirstConsumer
